### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by PrimordialOcean** [PrimordialOcean/my-public-tasks#2]
- [ ] 投稿論文作成
  - [ ] Introdcutionの修正
    - [ ] Cooper et al. 2017 EPSLを読む
    - [ ] 最新の研究について文献を追加
  - [ ] 柱状図の作成
    - [ ] Adachi 2012の修論を参考に北壁の柱状図Okp1-5を作成
    - [ ] 五色岳山頂付近の柱状図Okp5上部を作成
    - [ ] 柱状図に露頭写真を追加
  - [ ] Two-pyroxene thermometerの修正
    - [ ] KD値の変更の反映：EPMAがすぐに使えないのでヒストグラムを参考に計算
    - [ ] 温度の修正に合わせて拡散計算の再計算
  - [ ] Discussionの修正
    - [ ] 成因論の話題が多いのでzoningを調べることでpre-eruptiveのどういったことが分かってきたかを示す
    - [ ] 累帯構造の解析についてKahl 2015 J Petrolの手法を説明に追加
    - [ ] 鉱物相の共生関係の図を修正
    - [ ] 供給系の概念図を修正
- [ ] 今後の研究の準備
  - [ ] LA-ICP-MS分析用の斜長石結晶を選定
  - [ ] 分離結晶からマウント試料を作成
  - [ ] MELTS解析用プログラムの作成：線形補間モデルを修正
